// Generated by gencpp from file interbotix_sdk/RobotInfoRequest.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_SDK_MESSAGE_ROBOTINFOREQUEST_H
#define INTERBOTIX_SDK_MESSAGE_ROBOTINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interbotix_sdk
{
template <class ContainerAllocator>
struct RobotInfoRequest_
{
  typedef RobotInfoRequest_<ContainerAllocator> Type;

  RobotInfoRequest_()
    {
    }
  RobotInfoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotInfoRequest_

typedef ::interbotix_sdk::RobotInfoRequest_<std::allocator<void> > RobotInfoRequest;

typedef boost::shared_ptr< ::interbotix_sdk::RobotInfoRequest > RobotInfoRequestPtr;
typedef boost::shared_ptr< ::interbotix_sdk::RobotInfoRequest const> RobotInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace interbotix_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_sdk/RobotInfoRequest";
  }

  static const char* value(const ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Get robot information\n"
"#\n"
"# Note that all data that is returned in a vector is organized such that each index\n"
"# corresponds to the joint at the same index as it appears in the joint_states topic.\n"
"# Gripper info is NOT included in the vectors.\n"
"#\n"
"# Multiple types of robot information are provided, including:\n"
"#   1) joint_names - the names of all joints in the robot\n"
"#   2) joint_ids - the Dynamixel IDs for all joints in the robot\n"
"#   3) lower_joint_limits - the lower joint limits in radians (taken from URDF)\n"
"#   4) upper_joint_limits - the upper joint limits in radians (taken from URDF)\n"
"#   5) velocity_limits - the velocity limits in rad/s (taken from URDF)\n"
"#   6) lower_gripper_limit - the lower gripper limit in radians (taken from URDF)\n"
"#   7) upper_gripper_limit - the upper gripper limit in radians (taken from URDF)\n"
"#   8) use_gripper - True if the driver node can control the gripper - otherwise, False\n"
"#   9) home_pos - home position for each robot; essentially commands all joints\n"
"#                 (excluding gripper) to 0 radians (taken from arm_poses.h)\n"
"#   10) sleep_pos - sleep position for each robot; essentially commands all joints\n"
"#                   (excluding gripper) to a specific position in radians so that\n"
"#                   if the driver node is shutdown (which torques off all motors),\n"
"#                   the arm doesn't come crashing down (taken from arm_poses.h)\n"
"#   11) num_joints - the number of joints in the arm (excluding gripper)\n"
"\n"
;
  }

  static const char* value(const ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::interbotix_sdk::RobotInfoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_SDK_MESSAGE_ROBOTINFOREQUEST_H
