// Generated by gencpp from file testing_environment_moveit/CustomPositionResponse.msg
// DO NOT EDIT!


#ifndef TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITIONRESPONSE_H
#define TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testing_environment_moveit
{
template <class ContainerAllocator>
struct CustomPositionResponse_
{
  typedef CustomPositionResponse_<ContainerAllocator> Type;

  CustomPositionResponse_()
    {
    }
  CustomPositionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomPositionResponse_

typedef ::testing_environment_moveit::CustomPositionResponse_<std::allocator<void> > CustomPositionResponse;

typedef boost::shared_ptr< ::testing_environment_moveit::CustomPositionResponse > CustomPositionResponsePtr;
typedef boost::shared_ptr< ::testing_environment_moveit::CustomPositionResponse const> CustomPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace testing_environment_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testing_environment_moveit/CustomPositionResponse";
  }

  static const char* value(const ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::testing_environment_moveit::CustomPositionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITIONRESPONSE_H
