// Generated by gencpp from file testing_environment_moveit/CustomPosition.msg
// DO NOT EDIT!


#ifndef TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITION_H
#define TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITION_H

#include <ros/service_traits.h>


#include <testing_environment_moveit/CustomPositionRequest.h>
#include <testing_environment_moveit/CustomPositionResponse.h>


namespace testing_environment_moveit
{

struct CustomPosition
{

typedef CustomPositionRequest Request;
typedef CustomPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomPosition
} // namespace testing_environment_moveit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_environment_moveit::CustomPosition > {
  static const char* value()
  {
    return "23304a51cb2971aef33a4c038286d08b";
  }

  static const char* value(const ::testing_environment_moveit::CustomPosition&) { return value(); }
};

template<>
struct DataType< ::testing_environment_moveit::CustomPosition > {
  static const char* value()
  {
    return "testing_environment_moveit/CustomPosition";
  }

  static const char* value(const ::testing_environment_moveit::CustomPosition&) { return value(); }
};


// service_traits::MD5Sum< ::testing_environment_moveit::CustomPositionRequest> should match
// service_traits::MD5Sum< ::testing_environment_moveit::CustomPosition >
template<>
struct MD5Sum< ::testing_environment_moveit::CustomPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_environment_moveit::CustomPosition >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_environment_moveit::CustomPositionRequest> should match
// service_traits::DataType< ::testing_environment_moveit::CustomPosition >
template<>
struct DataType< ::testing_environment_moveit::CustomPositionRequest>
{
  static const char* value()
  {
    return DataType< ::testing_environment_moveit::CustomPosition >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_environment_moveit::CustomPositionResponse> should match
// service_traits::MD5Sum< ::testing_environment_moveit::CustomPosition >
template<>
struct MD5Sum< ::testing_environment_moveit::CustomPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_environment_moveit::CustomPosition >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_environment_moveit::CustomPositionResponse> should match
// service_traits::DataType< ::testing_environment_moveit::CustomPosition >
template<>
struct DataType< ::testing_environment_moveit::CustomPositionResponse>
{
  static const char* value()
  {
    return DataType< ::testing_environment_moveit::CustomPosition >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMPOSITION_H
