// Generated by gencpp from file testing_environment_moveit/CustomAngle.msg
// DO NOT EDIT!


#ifndef TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMANGLE_H
#define TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMANGLE_H

#include <ros/service_traits.h>


#include <testing_environment_moveit/CustomAngleRequest.h>
#include <testing_environment_moveit/CustomAngleResponse.h>


namespace testing_environment_moveit
{

struct CustomAngle
{

typedef CustomAngleRequest Request;
typedef CustomAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomAngle
} // namespace testing_environment_moveit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_environment_moveit::CustomAngle > {
  static const char* value()
  {
    return "a04862b47749bf3d91cb040c5b55f914";
  }

  static const char* value(const ::testing_environment_moveit::CustomAngle&) { return value(); }
};

template<>
struct DataType< ::testing_environment_moveit::CustomAngle > {
  static const char* value()
  {
    return "testing_environment_moveit/CustomAngle";
  }

  static const char* value(const ::testing_environment_moveit::CustomAngle&) { return value(); }
};


// service_traits::MD5Sum< ::testing_environment_moveit::CustomAngleRequest> should match
// service_traits::MD5Sum< ::testing_environment_moveit::CustomAngle >
template<>
struct MD5Sum< ::testing_environment_moveit::CustomAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_environment_moveit::CustomAngle >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_environment_moveit::CustomAngleRequest> should match
// service_traits::DataType< ::testing_environment_moveit::CustomAngle >
template<>
struct DataType< ::testing_environment_moveit::CustomAngleRequest>
{
  static const char* value()
  {
    return DataType< ::testing_environment_moveit::CustomAngle >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_environment_moveit::CustomAngleResponse> should match
// service_traits::MD5Sum< ::testing_environment_moveit::CustomAngle >
template<>
struct MD5Sum< ::testing_environment_moveit::CustomAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_environment_moveit::CustomAngle >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_environment_moveit::CustomAngleResponse> should match
// service_traits::DataType< ::testing_environment_moveit::CustomAngle >
template<>
struct DataType< ::testing_environment_moveit::CustomAngleResponse>
{
  static const char* value()
  {
    return DataType< ::testing_environment_moveit::CustomAngle >::value();
  }
  static const char* value(const ::testing_environment_moveit::CustomAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_ENVIRONMENT_MOVEIT_MESSAGE_CUSTOMANGLE_H
