(cl:in-package interbotix_sdk-srv)
(cl:export '(ARM_MODE-VAL
          ARM_MODE
          USE_CUSTOM_ARM_PROFILES-VAL
          USE_CUSTOM_ARM_PROFILES
          ARM_PROFILE_VELOCITY-VAL
          ARM_PROFILE_VELOCITY
          ARM_PROFILE_ACCELERATION-VAL
          ARM_PROFILE_ACCELERATION
          GRIPPER_MODE-VAL
          GRIPPER_MODE
          USE_CUSTOM_GRIPPER_PROFILES-VAL
          USE_CUSTOM_GRIPPER_PROFILES
          GRIPPER_PROFILE_VELOCITY-VAL
          GRIPPER_PROFILE_VELOCITY
          GRIPPER_PROFILE_ACCELERATION-VAL
          GRIPPER_PROFILE_ACCELERATION
))