(cl:defpackage testing_environment_moveit-srv
  (:use )
  (:export
   "CUSTOMANGLE"
   "<CUSTOMANGLE-REQUEST>"
   "CUSTOMANGLE-REQUEST"
   "<CUSTOMANGLE-RESPONSE>"
   "CUSTOMANGLE-RESPONSE"
   "CUSTOMPOSITION"
   "<CUSTOMPOSITION-REQUEST>"
   "CUSTOMPOSITION-REQUEST"
   "<CUSTOMPOSITION-RESPONSE>"
   "CUSTOMPOSITION-RESPONSE"
  ))

