# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from testing_environment_moveit/CustomPositionRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CustomPositionRequest(genpy.Message):
  _md5sum = "23304a51cb2971aef33a4c038286d08b"
  _type = "testing_environment_moveit/CustomPositionRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# x,y,z and yaw angle for arm A with respect to origin
float64 arm_a_x_pos
float64 arm_a_y_pos
float64 arm_a_z_pos

# x,y,z and yaw angle for arm B with respect to origin
float64 arm_b_x_pos
float64 arm_b_y_pos
float64 arm_b_z_pos
"""
  __slots__ = ['arm_a_x_pos','arm_a_y_pos','arm_a_z_pos','arm_b_x_pos','arm_b_y_pos','arm_b_z_pos']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm_a_x_pos,arm_a_y_pos,arm_a_z_pos,arm_b_x_pos,arm_b_y_pos,arm_b_z_pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CustomPositionRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.arm_a_x_pos is None:
        self.arm_a_x_pos = 0.
      if self.arm_a_y_pos is None:
        self.arm_a_y_pos = 0.
      if self.arm_a_z_pos is None:
        self.arm_a_z_pos = 0.
      if self.arm_b_x_pos is None:
        self.arm_b_x_pos = 0.
      if self.arm_b_y_pos is None:
        self.arm_b_y_pos = 0.
      if self.arm_b_z_pos is None:
        self.arm_b_z_pos = 0.
    else:
      self.arm_a_x_pos = 0.
      self.arm_a_y_pos = 0.
      self.arm_a_z_pos = 0.
      self.arm_b_x_pos = 0.
      self.arm_b_y_pos = 0.
      self.arm_b_z_pos = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.arm_a_x_pos, _x.arm_a_y_pos, _x.arm_a_z_pos, _x.arm_b_x_pos, _x.arm_b_y_pos, _x.arm_b_z_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.arm_a_x_pos, _x.arm_a_y_pos, _x.arm_a_z_pos, _x.arm_b_x_pos, _x.arm_b_y_pos, _x.arm_b_z_pos,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.arm_a_x_pos, _x.arm_a_y_pos, _x.arm_a_z_pos, _x.arm_b_x_pos, _x.arm_b_y_pos, _x.arm_b_z_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.arm_a_x_pos, _x.arm_a_y_pos, _x.arm_a_z_pos, _x.arm_b_x_pos, _x.arm_b_y_pos, _x.arm_b_z_pos,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from testing_environment_moveit/CustomPositionResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CustomPositionResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "testing_environment_moveit/CustomPositionResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CustomPositionResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class CustomPosition(object):
  _type          = 'testing_environment_moveit/CustomPosition'
  _md5sum = '23304a51cb2971aef33a4c038286d08b'
  _request_class  = CustomPositionRequest
  _response_class = CustomPositionResponse
